name = "memory-note"
type = "javascript"
main = "src/index.tsx"
workers_dev = false
kv_namespaces = [
    { binding = "MEMORY_NOTE", id = "ed18c0bc46ba467683048804406dcbf1" }
]
compatibility_date = "2023-01-01"
compatibility_flags = [ "nodejs_compat" ]
